# Configuración principal de la aplicación
spring:
  application:
    name: automovil-unite
  
  # Configuración de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/automovil_unite?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: TokisakiKurumi12345%
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuración de JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  
  # Configuración de Flyway para migraciones
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  # Configuración para subida de archivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Configuración de email
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tu-email@gmail.com}
    password: ${MAIL_PASSWORD:tu-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Configuración del servidor
server:
  port: ${PORT:8080}
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

# Configuraciones propias de la aplicación
app:
  # Configuración de JWT para seguridad
  jwt:
    secret: ${JWT_SECRET:cambiarEstaClaveSecretaEnProduccionPorqueDebe}
    expiration: 86400000  # 24 horas
    refresh-expiration: 604800000  # 7 días
    header: Authorization
    prefix: Bearer
  
  # Configuración de almacenamiento
  storage:
    location: ${STORAGE_LOCATION:uploads}
  
  # Configuración de CORS
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  
  # Configuración de seguridad
  security:
    password-strength:
      min-length: 8
      require-digit: true
      require-lowercase: true
      require-uppercase: true
      require-special-char: true
    encryption-key: ${ENCRYPTION_KEY:Ab76GhPq23ZxYw9kLmNoBpRsTuVv}
  
  # Frontend URL para links en emails, etc.
  frontend-url: ${FRONTEND_URL:http://localhost:4200}

# Configuración de logging
logging:
  level:
    root: INFO
    com.vision_rent.automovil_unite: DEBUG
    org.hibernate.SQL: ${LOG_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_SQL_PARAMS:TRACE}